### ISSUE TITLE
Its.Log.Monitoring: monitors with signature async Task throw exceptions

### ISSUE THREAD

**Issue by PhillipPruett** [jonsequitur/Its.Log#36]
Its.Log.Monitoring: monitors with signature async Task throw exceptions

{"Message":"Cannot implicitly convert type 'void' to 'object'","Exception":"{ RuntimeBinderException: Message = Cannot implicitly convert type 'void' to 'object' | Data = {  } | InnerException = [null] | TargetSite = System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object) | StackTrace =    at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Its.Log.Monitoring.MonitoringTestController.<Run>d__1.MoveNext() in c:\Git\ItsLogPHP\Its.Log.Monitoring\MonitoringTestController.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() | HelpLink = [null] | Source = Anonymously Hosted DynamicMethods Assembly | HResult = -2146233088 }"} | Headers = { HttpContentHeaders: Allow = {  } | ContentDisposition = [null] | ContentEncoding = {  } | ContentLanguage = {  } | ContentLength = 3100 | ContentLocation = [null] | ContentMD5 = [null] | ContentRange = [null] | ContentType = application/json; charset=utf-8 | Expires = [null] | LastModified = [null] } }

**Comment by jonsequitur** [comment]
Fixed by https://github.com/jonsequitur/Its.Log/commit/7531bd3295f7c43eb5fbc4b38b16fa75dddef794
