### ISSUE TITLE
Telemetry_events_contain_timing is flaky 

### ISSUE THREAD

**Issue by PhillipPruett** [jonsequitur/Its.Log#38]
the assertion in Telemetry_events_contain_timing fails every now and then due to the timing being slightly off.

**Comment by PhillipPruett** [comment]
Expected value to be between 1000 and 1100, but found 996. 
   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in D:\Workspaces\FluentAssertions\Src\Shared\Execution\LateBoundTestFramework.cs:line 26

   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in D:\Workspaces\FluentAssertions\Src\Core\Execution\AssertionScope.cs:line 197

   at FluentAssertions.Numeric.NumericAssertions`1.BeInRange(T minimumValue, T maximumValue, String because, Object[] reasonArgs) in D:\Workspaces\FluentAssertions\Src\Core\Numeric\NumericAssertions.cs:line 270

   at Its.Log.Instrumentation.UnitTests.TelemetryTests.<Telemetry_events_contain_timing>d__7.MoveNext()

   at NUnit.Framework.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)

   at NUnit.Core.NUnitAsyncTestMethod.RunTestMethod()

**Comment by PhillipPruett** [comment]
blocking my appveyor build so i went ahead and made its assertion a bit less specific. hopefully that settles it down.

**Comment by PhillipPruett** [comment]
fixed
